SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SampleTable136] (
		[PersonID]         [int] NULL,
		[LastName]         [varchar](255) NULL,
		[FirstName]        [varchar](255) NULL,
		[Address]          [varchar](255) NULL,
		[City]             [varchar](255) NULL,
		[column_new1]      [varchar](1) NULL,
		[column_new2]      [varchar](1) NULL,
		[column_new3]      [varchar](1) NULL,
		[column_new5]      [varchar](1) NULL,
		[column_new6]      [varchar](1) NULL,
		[column_new7]      [varchar](1) NULL,
		[column_new8]      [varchar](1) NULL,
		[column_new9]      [varchar](1) NULL,
		[column_new10]     [varchar](1) NULL,
		[column_new11]     [varchar](1) NULL,
		[column_new12]     [varchar](1) NULL,
		[column_new13]     [varchar](1) NULL,
		[column_new14]     [varchar](1) NULL,
		[column_new15]     [varchar](1) NULL,
		[column_new16]     [varchar](1) NULL,
		[column_new17]     [varchar](1) NULL,
		[column_new18]     [varchar](1) NULL,
		[column_new19]     [varchar](1) NULL,
		[column_new20]     [varchar](1) NULL,
		[column_new21]     [varchar](1) NULL,
		[column_new42]     [varchar](1) NULL,
		[column_new43]     [varchar](1) NULL,
		[column_new44]     [varchar](1) NULL,
		[column_new45]     [varchar](1) NULL,
		[column_new46]     [varchar](1) NULL,
		[column_new47]     [varchar](1) NULL,
		[column_new48]     [varchar](1) NULL,
		[column_new49]     [varchar](1) NULL,
		[column_new50]     [varchar](1) NULL,
		[column_new51]     [varchar](1) NULL,
		[column_new52]     [varchar](1) NULL,
		[column_new53]     [varchar](1) NULL,
		[column_new54]     [varchar](1) NULL,
		[column_new55]     [varchar](1) NULL
)
GO
