SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SampleTable174] (
		[PersonID]         [int] NULL,
		[LastName]         [varchar](255) NULL,
		[FirstName]        [varchar](255) NULL,
		[Address]          [varchar](255) NULL,
		[City]             [varchar](255) NULL,
		[column_new1]      [varchar](1) NULL,
		[column_new2]      [varchar](1) NULL,
		[column_new3]      [varchar](1) NULL,
		[column_new6]      [varchar](1) NULL,
		[column_new7]      [varchar](1) NULL,
		[column_new8]      [varchar](1) NULL,
		[column_new9]      [varchar](1) NULL,
		[column_new11]     [varchar](1) NULL,
		[column_new12]     [varchar](1) NULL,
		[column_new13]     [varchar](1) NULL,
		[column_new14]     [varchar](1) NULL,
		[column_new15]     [varchar](1) NULL,
		[column_new16]     [varchar](1) NULL,
		[column_new17]     [varchar](1) NULL,
		[column_new18]     [varchar](1) NULL,
		[column_new19]     [varchar](1) NULL,
		[column_new20]     [varchar](1) NULL,
		[column_new21]     [varchar](1) NULL,
		[column_new41]     [varchar](1) NULL,
		[column_new45]     [varchar](1) NULL,
		[column_new46]     [varchar](1) NULL,
		[column_new47]     [varchar](1) NULL,
		[column_new49]     [varchar](1) NULL,
		[column_new50]     [varchar](1) NULL,
		[column_new52]     [varchar](1) NULL,
		[column_new54]     [varchar](1) NULL,
		[column_new56]     [varchar](1) NULL,
		[column_new58]     [varchar](1) NULL,
		[column_new60]     [varchar](1) NULL,
		[column_new63]     [varchar](1) NULL,
		[column_new64]     [varchar](1) NULL,
		[column_new65]     [varchar](1) NULL,
		[column_new66]     [varchar](1) NULL,
		[column_new67]     [varchar](1) NULL,
		[column_new68]     [varchar](1) NULL
)
GO
