SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [ApexSQL].[fnToOffset](@date datetimeoffset) 
RETURNS datetimeoffset(7) 
AS
BEGIN
	return TODATETIMEOFFSET(@date, DATEPART(TZ,SYSDATETIMEOFFSET()))
END
GO
